name: Auto Commit Machine
on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minute
  push:
    branches: [main]
jobs:
  make-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add a line to the log
      run: echo "Commit at $(date)" >> commit-log.txt
    - name: Commit and push
      run: |
        git config --global user.name "Auto Commit Bot"
        git config --global user.email "bot@commits.com"
        git add commit-log.txt
        git commit -m "Auto commit on $(date)"
        git push
